# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Tag.create(name: "General Museum")
Tag.create(name: "Chicago")
Tag.create(name: "Temporary")
Tag.create(name: "Permanent")
Tag.create(name: "Exhibition")
Tag.create(name: "Gift Shop")

Tag.create(name: "Art Museums")
Tag.create(name: "Chicago")
Tag.create(name: "Art")
Tag.create(name: "Art Museum")
Tag.create(name: "Modern Art")
Tag.create(name: "Contemporary Art")
Tag.create(name: "European Art")
Tag.create(name: "American Art")
Tag.create(name: "Indian Art")
Tag.create(name: "Asian Art")
Tag.create(name: "African Art")
Tag.create(name: "Decorative Arts")
Tag.create(name: "Prints")
Tag.create(name: "Drawings")
Tag.create(name: "Monet")
Tag.create(name: "Van Gogh")
Tag.create(name: "Warhol")
Tag.create(name: "Pollack")
Tag.create(name: "Picasso")
Tag.create(name: "Painting")
Tag.create(name: "Impressionism")
Tag.create(name: "Abstract Expressionism")
Tag.create(name: "Cubism")
Tag.create(name: "Painting")
Tag.create(name: "Photography")
Tag.create(name: "Architecture")
Tag.create(name: "Design")
Tag.create(name: "Artist Talk")
Tag.create(name: "Lecture")
Tag.create(name: "Film")
Tag.create(name: "Public Art")
Tag.create(name: "Performance")
Tag.create(name: "Theater")
Tag.create(name: "Dance")
Tag.create(name: "Music")
Tag.create(name: "Experimental")
Tag.create(name: "Installation")

Tag.create(name: "Natural History/History Museum")
Tag.create(name: "ChicagoHistory")
Tag.create(name: "Natural History")
Tag.create(name: "Ancient History")
Tag.create(name: "Ancient Culture")
Tag.create(name: "Science")
Tag.create(name: "Nature")
Tag.create(name: "Animals")
Tag.create(name: "Dinosaur")
Tag.create(name: "Conservation")

Tag.create(name: "Science Museum")
Tag.create(name: "Science")
Tag.create(name: "Nature")
Tag.create(name: "Technology")
Tag.create(name: "Industry")
Tag.create(name: "Transportation")
Tag.create(name: "Trains")
Tag.create(name: "Planes")

Tag.create(name: "Planetarium")
Tag.create(name: "Space")

Tag.create(name: "Aquarium")
Tag.create(name: "Science")
Tag.create(name: "Nature")
Tag.create(name: "Animals")
Tag.create(name: "Oceanlife")
Tag.create(name: "Wildlife")
Tag.create(name: "Habitat")
Tag.create(name: "Dolphins")

Tag.create(name: "Zoo")
Tag.create(name: "Science")
Tag.create(name: "Nature")
Tag.create(name: "Animals")
Tag.create(name: "Wildlife")
Tag.create(name: "Habitat")
Tag.create(name: "Conservation")
