# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Tag.create(category: "Type of Museum", name: "Art")
Tag.create(category: "Type of Art", name: "Modern Art")
Tag.create(category: "Type of Art", name: "Contemporary Art")
Tag.create(category: "Type of Art", name: "European Art")
Tag.create(category: "Type of Art", name: "American Art")
Tag.create(category: "Type of Art", name: "Indian Art")
Tag.create(category: "Type of Art", name: "Asian Art")
Tag.create(category: "Type of Art", name: "African Art")
Tag.create(category: "Type of Art", name: "Decorative Arts")
Tag.create(category: "Medium", name: "Prints")
Tag.create(category: "Medium", name: "Drawings")
# Tag.create(category: name: "Monet")
# Tag.create(category: name: "Van Gogh")
# Tag.create(category: name: "Warhol")
# Tag.create(category: name: "Pollack")
# Tag.create(category: name: "Picasso")
Tag.create(category: "Medium", name: "Painting")
Tag.create(category: "Type of Art", name: "Impressionism")
Tag.create(category: "Type of Art", name: "Abstract Expressionism")
Tag.create(category: "Type of Art", name: "Cubism")
Tag.create(category: "Medium", name: "Photography")
Tag.create(category: "Medium", name: "Architecture")
Tag.create(category: "Medium", name: "Design")
Tag.create(category: "Misc", name: "Artist Talk")
Tag.create(category: "Misc", name: "Lecture")
Tag.create(category: "Medium", name: "Film")
Tag.create(category: "Medium", name: "Public Art")
Tag.create(category: "Medium", name: "Performance")
Tag.create(category: "Medium", name: "Theater")
Tag.create(category: "Medium", name: "Dance")
Tag.create(category: "Medium", name: "Music")
Tag.create(category: "Medium", name: "Experimental")
Tag.create(category: "Medium", name: "Installation")

Tag.create(category: "Type of Museum", name: "Natural History")
Tag.create(category: "Type of Museum", name: "ChicagoHistory")
Tag.create(category: "Type of Museum", name: "Natural History")
Tag.create(category: "Type of Museum", name: "Ancient History")
Tag.create(category: "Type of Museum", name: "Ancient Culture")
Tag.create(category: "Type of Museum", name: "Science")
Tag.create(category: "Type of Museum", name: "Nature")
Tag.create(category: "Misc", name: "Animals")
Tag.create(category: "Misc", name: "Dinosaur")
Tag.create(category: "Misc", name: "Conservation")

Tag.create(category: "Type of Museum", name: "Science Museum")
Tag.create(category: "Misc", name: "Technology")
Tag.create(category: "Misc", name: "Industry")
Tag.create(category: "Misc", name: "Transportation")
Tag.create(category: "Misc", name: "Trains")
Tag.create(category: "Misc", name: "Planes")

Tag.create(category: "Type of Museum", name: "Planetarium")
Tag.create(category: "Type of Museum", name: "Space")

Tag.create(category: "Type of Museum", name: "Aquarium")
Tag.create(category: "Misc", name: "Oceanlife")
Tag.create(category: "Misc", name: "Wildlife")
Tag.create(category: "Misc", name: "Habitat")
Tag.create(category: "Misc", name: "Dolphins")

Tag.create(category: "Type of Museum", name: "Zoo")
